class ArbSorter {
    splitter;
    ords;
    vals;
    /**
     * Create a new `ArbSorter`.
     * @\param order The list of all graphs used, in the order they are to be
     * sorted, separated by whitespace.
     */
    constructor(order) {
        const graphs = order.split(/\s+/gu);
        const splitOrder = [...graphs].sort((a, b) => b.length - a.length);
        this.splitter = new RegExp(`(${splitOrder.join('|')}|.)`, 'gu');
        this.ords = {};
        this.vals = [];
        for (const i in graphs) {
            this.ords[graphs[i]] = +i;
            this.vals.push(graphs[i]);
        }
    }
    /**
     * Convert a word to an array of numbers, for better sorting.
     * @\param word The original word, as a string.
     * @\returns A list of numbers based on the sort order.
     */
    wordAsValues(word) {
        const splitWord = this.split(word);
        const arrayedWord = splitWord.map(char => this.ords[char]);
        if (arrayedWord.includes(undefined)) {
            throw new Error(`word with unknown letter: '${word}'.\n`
                + 'A filter or assimilation might have caused this.');
        }
        return arrayedWord;
    }
    /**
     * Convert the array of numbers generated by `wordAsValues()` back to a
     * word.
     * @\param values The list of numbers based on the sord order.
     * @\returns The original word, as a string.
     */
    valuesAsWord(values) {
        return values.map(el => this.vals[el])
            .join('');
    }
    /**
     * Split a word into its graphs.
     * @\param word The word to be split.
     * @\returns An array of short strings, each one representing a single
     * grapheme or multigraph.
     */
    split(word) {
        return word.split(this.splitter)
            .filter(Boolean);
    }
    /**
     * Sort a list of words.
     * @\param list The list of words to be sorted.
     * @\returns A sorted copy of the list.
     */
    sort(list) {
        const l2 = list.filter(el => el !== '').map(this.wordAsValues, this);
        l2.sort((a, b) => {
            for (let i = 0; i < Math.min(a.length, b.length); ++i) {
                if (a[i] !== b[i]) {
                    return a[i] - b[i];
                }
            }
            return a.length - b.length;
        });
        return l2.map(this.valuesAsWord, this);
    }
}

export default ArbSorter;